### ISSUE TITLE
Errors resizing the window and screen object

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/arStudio#20]
The canvas errors seems to be fixed but i receive yet this messages in the console while trying to resize the vieport: 

`window.orientation undefined screen.orientation [object ScreenOrientation]`

that should printed only if the arController exist, but i closed the player tab so i suppose the arController is still available, I think should instead be destroyed.

_Originally posted by @kalwalt in https://github.com/augmentmy-world/arStudio/pull/19#issuecomment-582001282_

**Comment by kalwalt** [comment]
We solved the resize issue with #19 but not sure how to avoid this message yet...

**Comment by ThorstenBux** [comment]
Should be fixed with https://github.com/augmentmy-world/arStudio/pull/28
