### ISSUE TITLE
kalwalt/arStudio fix-for-resizing

### ISSUE THREAD

**Issue by ThorstenBux** [augmentmy-world/arStudio#24]
Hi @kalwalt,

is the https://github.com/kalwalt/arStudio/tree/fix-for-resizing
branch something that we can merge into master? If so could you please open a PR. Thanks.

**Comment by kalwalt** [comment]
@ThorstenBux it is merged in master with PR https://github.com/augmentmy-world/arStudio/pull/19

**Comment by ThorstenBux** [comment]
oh, so it was merged already. Thanks for clarification @kalwalt . I was browsing through your branches and didn't see a merge in the branch overview. All good then, thanks.
