### ISSUE TITLE
Issue while upgrading arStudio 

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/arStudio#33]
I started to upgrade to the latest of webglstudio, but after the merge i tested the editor and i received a lot of errors. I will left this [gist](https://gist.github.com/kalwalt/a1a47dd8066bea78f9d3b73a49e7e1da). My testing branch is https://github.com/kalwalt/arStudio/tree/upgrade-webglstudio

**Comment by ThorstenBux** [comment]
Thanks Walter,

I’ll take care of that in a bit. For me right now the urgent parts are
1. worker support
2. custom nft markers

Once we have that
3. Publishing the experience.

Then I can look into updating liteScene etc.

You mentioned that you might have time to get worker support integrated. Would you know when you would get to that?

Kind regards
Thorsten Bux

Sent from my iPhone

On 15/04/2020, at 3:39 AM, Walter Perdan <notifications@github.com> wrote:

﻿

I started to upgrade to the latest of webglstudio, but after the merge i tested the editor and i received a lot of errors. I will left this gist<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2Fkalwalt%2Fa1a47dd8066bea78f9d3b73a49e7e1da&data=02%7C01%7C%7C89bf26ecfc9749a9e9db08d7e089f665%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637224755461264558&sdata=kxmbNZg%2Ff1WeZMLJsBdvsUj1voEaJrMG7oATf9KCUTo%3D&reserved=0>. My testing branch is https://github.com/kalwalt/arStudio/tree/upgrade-webglstudio<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkalwalt%2FarStudio%2Ftree%2Fupgrade-webglstudio&data=02%7C01%7C%7C89bf26ecfc9749a9e9db08d7e089f665%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637224755461264558&sdata=HG7GFFY%2FByBTsOjGiiLOaTHMTdj6e8rNu%2Blkg%2F6G9Yg%3D&reserved=0>

**Comment by kalwalt** [comment]
Hi, @ThorstenBux i will start the worker part during these days, regarding the upgrade maybe i have done something wrong with the merge.

**Comment by ThorstenBux** [comment]
Awesome thanks 😊. As said I will look into merging it. Once custom nft is done. 🤩 Very grateful that you are supporting this project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
It's a pleasure! I prefer doing the worker part, is more creative... :smile:
