### ISSUE TITLE
Project publishing

### ISSUE THREAD

**Issue by ssemerikov** [augmentmy-world/arStudio#35]
I tried to publish my demo scene using your video instructions (thanks a lot!). Unfortunately, the only way when player is load the scene successfully, is to be logged at https://webarstudio.tripod-digital.co.nz/ at the same web browser. In any other case (another browser or private window) I got "Error loading scene: scene.json -> 0". Therefore, I can not really show my AR experience to any except me :(

**Comment by ThorstenBux** [comment]
Will take a look

Kind regards
Thorsten Bux

Sent from my iPhone

On 26/05/2020, at 2:23 AM, ssemerikov <notifications@github.com> wrote:

﻿

I tried to publish my demo scene using your video instructions (thanks a lot!). Unfortunately, the only way when player is load the scene successfully, is to be logged at https://webarstudio.tripod-digital.co.nz/<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwebarstudio.tripod-digital.co.nz%2F&data=02%7C01%7C%7C7fc107396403487face608d800b73816%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637260134198898569&sdata=tmLf2LszfTAxIyT0bt7h1fFVyRM6ePkVM2Ew4MirLhM%3D&reserved=0> at the same web browser. In any other case (another browser or private window) I got "Error loading scene: scene.json -> 0". Therefore, I can not really show my AR experience to any except me :(

**Comment by ThorstenBux** [comment]
Should be fixed now. Please also note that the project has moved to https://github.com/webarkit/WebAR-Studio
