### ISSUE TITLE
jquery libs included in src or as cdn links?

### ISSUE THREAD

**Issue by kalwalt** [augmentmy-world/arStudio#8]
jquery libs was missed and i provided with cdn links:
https://github.com/augmentmy-world/arStudio/blob/08583457e9969023168b86d0eefd24f37a151659/editor/index.html#L22-L23
what should be better? leave the cdn links or provide with sourced libs?

**Comment by ThorstenBux** [comment]
Copy of the lib I think is better. It is recommended most of the time from what I've read.

**Comment by kalwalt** [comment]
i will upload the libs soon. I need only to test them to be sure.

**Comment by kalwalt** [comment]
Solved with #13.
